-- Archives the computed Remarks column (Payroll Export > Auto Remarks +
-- Fold notes) for a given month, so it survives later changes to the
-- underlying data — a loan getting paid off, a rate changing, an entry
-- being deleted — none of which should silently rewrite what THIS
-- month's remarks actually said at the time.
--
-- Deliberately NOT re-implemented server-side: the remarks themselves are
-- already fully computed in the browser (Auto Remark Rules + Fold, see
-- _prBuildRemarksText in _src/app.js) every time the Export tab renders —
-- duplicating that logic in the backend would be a large, easy-to-drift
-- second copy of the same rules. Instead the ALREADY-computed table (one
-- row per person who has a non-empty remark: name, designation, remarks)
-- gets POSTed here as a plain JSON snapshot from a "Save to Remarks Log"
-- button on the Export tab, once per month — the smallest schema that
-- covers "Name / Post / Remarks for August" without inventing a new
-- calculation engine.
--
-- One row per (month, year) — saving again for a month you've already
-- saved replaces it, rather than piling up near-duplicate snapshots.
--
-- Run in Supabase SQL editor.

create table if not exists payroll.remarks_log (
  id bigint generated by default as identity primary key,
  run_id bigint references payroll.runs(id) on delete set null,
  month integer not null,
  year integer not null,
  rows jsonb not null default '[]'::jsonb, -- [{user_id, name, designation, remarks}, ...]
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (month, year)
);

grant select, insert, update, delete on payroll.remarks_log to service_role;
grant usage, select on all sequences in schema payroll to service_role;

notify pgrst, 'reload schema';
