-- Joining-date correction and promotion-history backfill from the real
-- Aug 2026 payroll sheets (SALARY OF SCHOOL / Salary Of College), matched by
-- name + designation cross-check with a hard safeguard requiring at least
-- one genuinely distinctive (non-common) shared name token -- an earlier
-- pass of this matching falsely merged some different people who share a
-- common surname/suffix and the same job title (e.g. two Security Guards),
-- which this version rejects instead. Per user instruction: the sheet is
-- treated as the source of truth. Generated by Claude, 2026-09-15.
--
-- Part 1: 1 person whose person_setup.joining_date held a
-- LATER date (a promotion/regrade date) instead of their true original
-- joining date.
--
-- Part 2: 11 person_grade_history rows backfilled for people
-- whose sheet shows 2+ stacked dates (joining + later promotion/regrade
-- events) not yet logged. Grade/step at each date is NOT stated in the
-- sheet's join-date column, so grade_id/step_id are left null (same
-- convention as the existing rows already in this table).
--
-- Run in Supabase SQL editor.

-- ===== Part 1: joining_date correction (1) =====
-- Md Jahidul Islam Jahid (42013142): 2013-09-09 -> 2013-10-09
update payroll.person_setup set joining_date = '2013-10-09' where user_id = '42013142';

-- ===== Part 2: person_grade_history backfill (11 rows) =====
insert into payroll.person_grade_history (user_id, grade_id, step_id, pay_type, effective_date, note) values
  ('12016164', null, null, 'regular', '2026-08-01', 'Promotion/role-change date from the 01 ST payroll sheet (August 2026), listed there as "Jannatul Ferdous" (G-11 Assistant Teacher); grade at this date not independently known.'),
  ('21995107', null, null, 'regular', '2007-07-20', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Md. Golam Mostofa" (Associate  Professor); grade at this date not independently known.'),
  ('21995107', null, null, 'regular', '2013-06-06', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Md. Golam Mostofa" (Associate  Professor); grade at this date not independently known.'),
  ('21995107', null, null, 'regular', '2024-07-31', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Md. Golam Mostofa" (Associate  Professor); grade at this date not independently known.'),
  ('21996105', null, null, 'regular', '2006-07-27', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Meah Mohammed. Yousuf Chy" (Professor); grade at this date not independently known.'),
  ('21996105', null, null, 'regular', '2010-01-01', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Meah Mohammed. Yousuf Chy" (Professor); grade at this date not independently known.'),
  ('21996105', null, null, 'regular', '2021-01-17', 'Promotion/role-change date from the 01 CT payroll sheet (August 2026), listed there as "Meah Mohammed. Yousuf Chy" (Professor); grade at this date not independently known.'),
  ('32009111', null, null, 'regular', '2025-09-21', 'Promotion/role-change date from the 01 SS payroll sheet (August 2026), listed there as "Md. Shah Alam" (Driver   Contractual); grade at this date not independently known.'),
  ('42000109', null, null, 'regular', '2023-11-01', 'Promotion/role-change date from the 01 CS payroll sheet (August 2026), listed there as "Md. Abdul Latif" (Driver (contractual)); grade at this date not independently known.'),
  ('42013142', null, null, 'regular', '2023-10-09', 'Promotion/role-change date from the 01 CS payroll sheet (August 2026), listed there as "Md. Jahidul Islam" (G-18 Security Guard); grade at this date not independently known.'),
  ('42025174', null, null, 'regular', '2026-11-11', 'Promotion/role-change date from the 01 CS payroll sheet (August 2026), listed there as "Joy Dash" (Bus Helper(Contractual)); grade at this date not independently known.');
